### ISSUE TITLE
contact details

### ISSUE THREAD

**Issue by mohancm** [mohancm100/device_lenovo_A7010a48#2]
Mohan CM
mohanmanjappa@gmal.com

**Comment by GuizaoBR** [comment]
Hello,
I trying compile RR 5.8.0 to my device with mt6753 with kernel stock 3.18.19+ but i stucked on bootlogo, you can help me to solve this problem?  
https://github.com/GuizaoBR/android_device_quantum_q5
Thanks for attention
Telegram user: @GuizaoBR

**Comment by mohancm** [comment]
i will take a look.
